// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ecoorbit_dotnet.Infrastructure.Data;

#nullable disable

namespace ecoorbit_dotnet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ecoorbit_dotnet.Domain.Entities.FireDetectionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ANALYZED_AT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("CONFIDENCE_SCORE");

                    b.Property<int>("FireDetected")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FIRE_DETECTED");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("NOTES");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RISK_LEVEL");

                    b.Property<Guid>("SatelliteImageId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("SATELLITE_IMAGE_ID");

                    b.HasKey("Id");

                    b.HasIndex("SatelliteImageId")
                        .IsUnique();

                    b.ToTable("FIRE_DETECTION_RESULTS", (string)null);
                });

            modelBuilder.Entity("ecoorbit_dotnet.Domain.Entities.SatelliteImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CAPTURED_AT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("IMAGE_URL");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("REGION");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("SUBMITTED_AT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SATELLITE_IMAGES", (string)null);
                });

            modelBuilder.Entity("ecoorbit_dotnet.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ROLE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("ecoorbit_dotnet.Domain.Entities.FireDetectionResult", b =>
                {
                    b.HasOne("ecoorbit_dotnet.Domain.Entities.SatelliteImage", "SatelliteImage")
                        .WithOne("DetectionResult")
                        .HasForeignKey("ecoorbit_dotnet.Domain.Entities.FireDetectionResult", "SatelliteImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SatelliteImage");
                });

            modelBuilder.Entity("ecoorbit_dotnet.Domain.Entities.SatelliteImage", b =>
                {
                    b.HasOne("ecoorbit_dotnet.Domain.Entities.User", "User")
                        .WithMany("SatelliteImages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecoorbit_dotnet.Domain.Entities.SatelliteImage", b =>
                {
                    b.Navigation("DetectionResult");
                });

            modelBuilder.Entity("ecoorbit_dotnet.Domain.Entities.User", b =>
                {
                    b.Navigation("SatelliteImages");
                });
#pragma warning restore 612, 618
        }
    }
}
